### PR TITLE
Adding status bar animation

### LINKED ISSUE #167: iOS7: Add option to animate status bar along with the navigation controller
First of all, awesome work!

There are several issues with using any kind of drawer controller on iOS7 together with the new transparent status bar. The custom status bar background view is an acceptable workaround, at the cost of losing some of the iOS7 aesthetic.

I'd really like to see something like what Mike Rundle has done in the Interesting app. The entire status bar is animated to the side, together with the navigation controller. 

Working web based example:
http://flyosity.com/interesting/

Would it be possible to do this with MMDrawerController? 

I'm not that well versed in UIKit development, but if no one else is up for it I'd like to try to implement this. I might need a pointer or two though.

Cheers!

### PR DESCRIPTION
**Pull request by Ded77**
Adding status bar animation. 
This will close #167.

### CODE REVIEW

**Comment by thomasbaldwin** [comment]
This used to work perfectly, but with xCode 7, if you're using your mouse and you move the side menu between open and close, the status bar won't stay aligned with the navigation bar. @Ded77 @hbmtw @mkruus Any suggestions on how I can fix this?

**Comment by thomasbaldwin** [comment]
Here's a screen recording of this in action. This didn't used to happen with the demo, which leads me to assume it's something with xCode 7 or me upgrading to El Capitan

https://youtu.be/hX4namxN4G0

**Comment by thomasbaldwin** [comment]
It turns out it's just the new iOS simulator being laggy with the status bar. it works fine on the phone

**Comment by Ded77** [comment]
@thomasbaldwin 
Hello, great if it is just a simulator glitch.
But remember, don't use this code in app that will be submitted on the AppStore. We use private API in this pull request.

**Comment by thomasbaldwin** [comment]
Hey @Ded77, any idea how GroupMe is doing it if they're not using the private API function?

cze7t

**Comment by Ded77** [comment]
@thomasbaldwin hummm, I think they are using private API !
As far as I know, the only safe way to do this is to make a screenshot of the screen and animate this screenshot [eg.](http://stackoverflow.com/a/19011013/3771801)
But that's not what they do (the clock is always up to date...).

For me, the proper way to do this is to hide the status bar with an animation [cf.](http://stackoverflow.com/questions/13624695/proper-way-to-hide-status-bar-on-ios-with-animation-and-resizing-root-view), like in the Slack app, but maybe that's not really what you want.

**Pull request closed without merging**
