### PR TITLE
Call removeFromParentViewController after removeFromSuperview in setCent...

### PR DESCRIPTION
**Pull request by long**
...erViewController to avoid EXC_BAD_ACCESS due to nil view value

Resolves an encountered issue with NappDrawer (https://github.com/viezel/NappDrawer/issues/139) where setting the center window would result in an app crash

### CODE REVIEW

**Comment by caspahouzer** [comment]
:+1:

**Comment by mpociot** [comment]
:+1:

**Comment by kcharwood** [comment]
Sorry for just getting to this. I'll get this reviewed and tested this week!

**Comment by kcharwood** [comment]
Thanks!

**Comment by bjarkehs** [comment]
This causes quite a few issues for a project I'm maintaining. After updating to 0.6.0 from 0.5.7 I start experiencing that my viewControllers are not actually dealloc'ed. If I revert this specific change, then everything works as expected. Any ideas?

**Comment by moonvader** [comment]
same question about **viewControllers being actually dealloc'ed**

**Pull request merged**
