### PR TITLE
Add new configurable properties.

### PR DESCRIPTION
**Pull request by SanggeonPark**
Make configurable shadow and pan velocity x animation threshold

### CODE REVIEW

**Comment by kcharwood** [comment]
I'll get to this later this week! Thanks.

**Comment by kcharwood** [comment]
Related to #294

**Comment by kcharwood** [comment]
Related to #270

**Comment by SanggeonPark** [comment]
Should I add new examples for that?

**Comment by kcharwood** [comment]
Thanks. I took these changes in dd06fde, and did a little clean up!

:beers:

**Comment by SanggeonPark** [comment]
Thanks :)

**Pull request closed without merging**
